version: '3'
services:
   app:
      build:
         context: ./
         dockerfile: deploy/local/app/Dockerfile
      working_dir: /app/bpg
      volumes:
         - './:/app/bpg:cached'
         - '~/.composer/:/home/app/.composer/'
      environment:
         - PHP_IDE_CONFIG=serverName=px-bpg
      extra_hosts:
         - 'host.docker.internal:host-gateway'
      links:
         - database
         - redis
   database:
      image: 'postgres:11'
      volumes:
         - 'data-volume:/var/lib/postgresql/data'
      environment:
         - POSTGRES_PASSWORD=root
         - POSTGRES_DB=px-admin
         - POSTGRES_USER=root
      ports:
         - '${PXO_DOCKER_PG_PORT:-15433}:5432'
   nginx:
      image: 'nginx:alpine'
      volumes:
         - './:/app/bpg:cached'
         - './deploy/local/nginx/conf.d/:/etc/nginx/conf.d/:ro'
      ports:
         - '${PXO_DOCKER_HTTP_PORT:-8082}:80'
         - '${PXO_DOCKER_HTTP_SSL_PORT:-9443}:443'
         - '${PXO_DOCKER_HTTP_METRICS_PORT:-9090}:9090'
      links:
         - app
   redis:
      image: 'redis:5.0.5-alpine'
      command:
         - redis-server
         - '--appendonly'
         - 'yes'
      volumes:
         - 'redis-data:/data'
      ports:
         - '${PXO_DOCKER_REDIS_PORT:-46379}:6379'
volumes:
   data-volume: null
   paxful-data-volume: null
   redis-data: null
